# Generated by Django 5.2.7 on 2025-11-01 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='author_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subgenres', to='bookapp.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('publication_year', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('summary', models.TextField(blank=True)),
                ('cover_image', models.URLField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('book_type', models.CharField(choices=[('digital', 'Digital'), ('physical', 'Physical'), ('both', 'Both')], default='both', max_length=10)),
                ('stock', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('authors', models.ManyToManyField(related_name='books', to='bookapp.author')),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='bookapp.genre')),
            ],
            options={
                'ordering': ['-publication_year', 'title'],
            },
        ),
    ]
