# Generated by Django 5.2.7 on 2025-11-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0005_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
