# Generated by Django 5.2.7 on 2025-11-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0006_alter_author_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='book_type',
            field=models.CharField(choices=[('digital', 'Digital'), ('physical', 'Physical'), ('both', 'Both')], default='physical', max_length=10),
        ),
    ]
