# Generated by Django 5.2.7 on 2025-11-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0008_order_razorpay_order_id_order_razorpay_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_pdf',
            field=models.FileField(blank=True, null=True, upload_to='book_pdfs/'),
        ),
    ]
