# Generated by Django 5.2.7 on 2025-12-06 17:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0011_book_average_rating_book_rating_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.TextField(blank=True, help_text='Optional review text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings', to='bookapp.book')),
                ('order', models.ForeignKey(blank=True, help_text='The order in which this book was purchased', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='bookapp.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'book'], name='bookapp_use_user_id_588d3b_idx'), models.Index(fields=['book', 'rating'], name='bookapp_use_book_id_9d5402_idx'), models.Index(fields=['created_at'], name='bookapp_use_created_d8cfd2_idx')],
                'unique_together': {('user', 'book', 'order')},
            },
        ),
    ]
